[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = bodmer/TFT_eSPI
monitor_speed = 115200
upload_speed = 115200
build_flags =
  -DUSER_SETUP_LOADED=1
  -DST7789_DRIVER=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DTFT_MOSI=23
  -DTFT_SCLK=18
  -DTFT_CS=27
  -DTFT_DC=21
  -DTFT_RST=22
  -DTFT_BL=25
  -DTFT_BACKLIGHT_ON=HIGH
  -DTOUCH_CS=-1
  -DLOAD_GLCD=1
  -DSPI_FREQUENCY=40000000
; if the panel shows inverted colours, add: -DTFT_INVERSION_ON=1
